using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using GhostWarpPlayer = Content.Shared.Ghost.SharedGhostSystem.GhostWarpPlayer;
using GhostWarpPlace = Content.Shared.Ghost.SharedGhostSystem.GhostWarpPlace;
using GhostWarpGlobalAntagonist = Content.Shared.Ghost.SharedGhostSystem.GhostWarpGlobalAntagonist;

namespace Content.Client._Sunrise.UserInterface.Systems.Ghost.Controls;

[GenerateTypedNameReferences]
public sealed partial class SunriseGhostTargetWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private HashSet<GhostWarpPlayer> _playerWarps = [];
    private HashSet<GhostWarpPlace> _placeWarps = [];
    private HashSet<GhostWarpGlobalAntagonist> _antagonists = [];

    private readonly HashSet<GhostWarpPlayer> _alivePlayers = [];
    private readonly HashSet<GhostWarpPlayer> _leftPlayers = [];
    private readonly HashSet<GhostWarpPlayer> _deadPlayers = [];
    private readonly HashSet<GhostWarpPlayer> _ghostPlayers = [];

    public event Action<NetEntity>? WarpClicked;

    public SunriseGhostTargetWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void Populate()
    {
        GhostTeleportContainer.DisposeAllChildren();
        _playerWarps = GetSortedByName(_playerWarps);
        _placeWarps = GetSortedByName(_placeWarps);
        _antagonists = GetSortedByName(_antagonists);

        PlayersAllocation();
        AddButtons();
    }

    public void UpdateWarps(HashSet<GhostWarpPlayer> players, HashSet<GhostWarpPlace> places, HashSet<GhostWarpGlobalAntagonist> antagonists)
    {
        _playerWarps = players;
        _placeWarps = places;
        _antagonists = antagonists;
    }

    private void AddButtons()
    {
        AddAntagButtons(_antagonists, "ghost-teleport-menu-antagonists-label");

        // Живые
        AddPlayerButtons(_alivePlayers, "ghost-teleport-menu-alive-label");

        // Мертвые
        AddPlayerButtons(_deadPlayers, "ghost-teleport-menu-dead-label");

        // Призраки
        AddPlayerButtons(_ghostPlayers, "ghost-teleport-menu-ghosts-label");

        // Остальные
        AddPlayerButtons(_leftPlayers, "ghost-teleport-menu-left-label");
        AddPlaceButtons(_placeWarps, "ghost-teleport-menu-locations-label");
    }

    private void PlayersAllocation()
    {
        _alivePlayers.Clear();
        _deadPlayers.Clear();
        _leftPlayers.Clear();
        _ghostPlayers.Clear();

        foreach (var warp in _playerWarps)
        {
            if (warp.IsDead)
                _deadPlayers.Add(warp);
            else if (warp.IsLeft)
                _leftPlayers.Add(warp);
            else if (warp.IsAlive)
                _alivePlayers.Add(warp);
            else if (warp.IsGhost)
                _ghostPlayers.Add(warp);
        }
    }
}
